# Generated by Django 5.0.2 on 2024-03-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.FloatField(),
        ),
    ]
