# Generated by Django 5.0.2 on 2024-03-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personal'),
        ),
    ]
